### PR TITLE
fix(reactmultiemail.tsx): trim emails with space after comma

### PR DESCRIPTION
**Pull request by jhaltercmu2020**
trim emails with space after comma. If you copy something like: email1@domain.com, email2@domain.com, email3@domain.com the space is

### CODE REVIEW

**Comment by jhaltercmu2020** [comment]
@thomasJang Can you take a look? The reason why we need to make this change is because if you copy something like this:
```
email1@domain.com, email2@domain.com, email3@domain.com
```
the spaces are causing issues and if we trim the space everything works as expected. Let me know if you have any questions.

**Review by thomasJang — APPROVED** [review]

**Comment by thomasJang** [comment]
Yes!, I think this code don't make side effect.

**Comment by jhaltercmu2020** [comment]
@thomasJang Thanks, would you be able to tag a few others with approval access to review?

**Comment by thomasJang** [comment]
Thx. @jhaltercmu2020 1.0.18 is out

**Pull request merged**
